language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "nicoevgl"
    token:
      secure: 1345e89eb9b010377ccd803987805e9ee668b65f

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=NicoEvgl_Library_API -Dsonar.login=1345e89eb9b010377ccd803987805e9ee668b65f
