language: java

jdk:
  - openjdk11

dist: trusty

addons:
  sonarcloud:
    organization: "nicoevgl"
    token:
      secure: a8dd1b9e8f422f7d097c1a2b9e8a21c320a6d397

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean install sonar:sonar -Dsonar.login=a8dd1b9e8f422f7d097c1a2b9e8a21c320a6d397
